mybatis:
  # \u8BBE\u7F6E\u522B\u540D
  type-aliases-package: com.ims.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/app_ims
    username: root
    password: root
server:
  port: 8006
